In [74]:
import pandas as pd

data = pd.read_csv ('CleanedDataSet.csv')   
df = pd.DataFrame(data)
data.pop('Unnamed: 6')
print (df)


                                                 Tweet  \
0                 طلالة أنيقة وانثوية مجموعة لخريفشتاء   
1                       خر صيحة حقائب اليد فندي وغوتشي   
2    تشرف باري_غاليري بدعوتكم لحضور ومقابلة نجوى_مح...   
3    ستايلبنطال نامجون الجينز لصور بسعرجنيه استرلين...   
4    RTكريس Idolازياء كريس جميعها بربري المجموعه ال...   
..                                                 ...   
657  رق لحذف الملفات المستعصية الحذف برامج احيانا ت...   
658  رح فيديو مهم جدا حل لمشاكل الكومبيوتر تقوم بتص...   
659        ورة مسربة لـ فونتوضح شكل الأيقونات الرئيسية   
660                                                ورة   
661                                              مسربة   

                                     Snow_Ball_Stemmer  \
0                       طلال انيق وانثو مجموع خريفشتاء   
1                           خر صيح حقايب اليد فند غوتش   
2    تشرف اري_غالير دعو حضور مقابل نجوى_محمد خبيرة_...   
3    ستايلبنطال نامج جينز لصور سعرجن استرل مارك غوت...   
4    RTكريس I

In [75]:
mylist = df['ISRI_Stemmer']
mylist[:100]

0                             طلل نيق نثو جمع لخريفشتاء
1                               خر صيح حقب الد فند غوتش
2     شرف باري_غاليري دعو حضر قبل نجوى_محمد خبيرة_ال...
3     ستايلبنطال نمج جينز لصر بسعرجنيه رلي ارك غوتشي...
4     RTكريس Idolازياء كرس جمع ربر جمع اخيرهحذاءه دي...
                            ...                        
95                        رئط لقط صور وحش عملاق عمق حيط
96                          اعل دلل حرب نطق شرع حيء ليب
97                      حسن رضي الل عنه سبق عصر خدم ابس
98                                      حقك جمع شعب رطو
99    ن درب يكو درد قبل جيء دييغو يمو بقي فرق ادر غل...
Name: ISRI_Stemmer, Length: 100, dtype: object

In [76]:
from nltk.tokenize import word_tokenize
my_new_list=[]

for i in mylist:
    my_new_list.append(i)
my_list=my_new_list
print(len(my_list))
my_list[:100]

662


['طلل نيق نثو جمع لخريفشتاء',
 'خر صيح حقب الد فند غوتش',
 'شرف باري_غاليري دعو حضر قبل نجوى_محمد خبيرة_التجميل نقط بيع حضر جمل يومسبتمبر',
 'ستايلبنطال نمج جينز لصر بسعرجنيه رلي ارك غوتشيGUCCI عدل ريل سعد',
 'RTكريس Idolازياء كرس جمع ربر جمع اخيرهحذاءه ديداس اوريجنال نظر',
 'عرف حذء جمع كعب علي مسطحعبر ربط',
 'فلر اسد فخم',
 'بلغ لحج خلق الا انه ازل شيئ نيق',
 'فضل فلم شفت شهب حقك كيتس اين برم ديا هونكابهي كبه قام ذات دور اين برم جممميلو',
 'طقم نسي ارك معاساور دبل علب وكر ارك سعر ريل',
 'طقم نسي ارك شانيل وشو برد معاساور دبل سعرريالللطلب عالواتس',
 'ير احط',
 'يال جده بقي مدن شحن شنط_فندي_بولغاري_غوتشي_روبرتو_كفالي شنط_فندي شنط_تقليد_درجه_اولى شنط_بنات_الجامعة',
 'اشي شي جدد',
 'هل_ب عرض مزاجكعطر جلت بلك نسء بـريالتسوق',
 'خطو طبق كيج وسم خرف شتء وقع حيت',
 'خر صيح وضة حقب ربع',
 'بيه',
 'الل انه سوي نظر',
 'طلق جمع جدد زيء رجل جدد',
 'لسعووديات_مرهلاتساع نسي ارك غوتشيمع سور خوا وكر ضمن فقط بـ ريل',
 'قم خب_اول صناعة_تركية طلب_التواصل_عالواتس_أو_الدايركت_للجادين_فقط',
 'مزح اسم جينز'

In [7]:
from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist

all_words = []
for message in mylist:
    words = word_tokenize(message)
    for w in words:
        all_words.append(w)

all_words = FreqDist(all_words)
print(len(all_words))
all_words

2531


FreqDist({'امر': 35, 'علم': 33, 'لعب': 32, 'رئس': 29, 'جمع': 28, 'فضل': 27, 'عمل': 27, 'قدم': 25, 'عرف': 23, 'نفس': 23, ...})

In [8]:
vocab = [w for w,f in all_words.items() if f > 5]
print(len(vocab))
vocab

199


['جمع',
 'قبل',
 'جمل',
 'ارك',
 'ريل',
 'سعد',
 'نظر',
 'عرف',
 'علي',
 'ربط',
 'اسد',
 'فخم',
 'الا',
 'انه',
 'فضل',
 'فلم',
 'دور',
 'طقم',
 'شي',
 'جدد',
 'عرض',
 'طبق',
 'وقع',
 'ربع',
 'الل',
 'طلق',
 'فقط',
 'بـ',
 'اسم',
 'اخي',
 'كلب',
 'وجه',
 'ولل',
 'شكل',
 'اقل',
 'كتب',
 'عطر',
 'عبر',
 'صبح',
 'قدر',
 'خبر',
 'اي',
 'صور',
 'اخر',
 'شغل',
 'بدأ',
 'صغر',
 'بعد',
 'اول',
 'ستر',
 'كانت',
 'اني',
 'لبس',
 'يمكن',
 'شخص',
 'رهب',
 'نجم',
 'دخل',
 'الآ',
 'كبر',
 'امر',
 'حسب',
 'ابد',
 'غرب',
 'مو',
 'قرب',
 'تقل',
 'حكم',
 'انا',
 'جرب',
 'طلب',
 'عشن',
 'اشف',
 'بطل',
 'صدر',
 'رئس',
 'انت',
 'نزل',
 'ولد',
 'قدم',
 'شرك',
 'علم',
 'هتف',
 'ذكة',
 'نفس',
 'مش',
 'عمل',
 'كوب',
 'ورد',
 'وغل',
 'سرع',
 'بيت',
 'ناس',
 'اعل',
 'جهز',
 'صوت',
 'ن',
 'يقل',
 'كلم',
 'عرب',
 'حمر',
 'سحب',
 'عنه',
 'لى',
 'حدث',
 'حمل',
 'درويد',
 'عند',
 'وحد',
 'رجم',
 'شهد',
 'خدم',
 'جدا',
 'دول',
 'خلف',
 'سبق',
 'شعب',
 'درب',
 'فرق',
 'او',
 'كنت',
 'رجع',
 'اليوم',
 'عدم',
 'بحث',
 'ت

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from nltk.classify.scikitlearn import SklearnClassifier
from sklearn.svm import SVC

<h1>N-grams<h1>

In [54]:
from sklearn.feature_extraction.text import CountVectorizer
## Get Features
### Get n-gram character (2,3,4,5)
count_vect_char = CountVectorizer(analyzer='char', ngram_range=(2,5), min_df=2, max_features=10000)
### Get n-gram word (1,2,3)
count_vect_word = CountVectorizer(analyzer='word', ngram_range=(1,3), min_df=2, max_features=10000)

In [55]:
from sklearn.preprocessing import LabelEncoder
l = LabelEncoder()
y = l.fit_transform(df[['feeling']])
y

C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 1, 2, 1, 1, 1, 2, 2, 2, 1, 1, 2, 1, 2, 2, 1, 2, 2, 1, 1, 1, 1,
       1, 2, 1, 1, 2, 2, 0, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 0, 1, 2, 1, 2,
       2, 1, 2, 1, 2, 1, 2, 2, 1, 0, 1, 2, 2, 2, 2, 1, 2, 2, 0, 1, 2, 2,
       2, 1, 2, 1, 1, 1, 2, 1, 1, 0, 1, 0, 1, 0, 1, 2, 2, 2, 1, 1, 2, 1,
       2, 1, 1, 1, 2, 2, 0, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1,
       2, 1, 2, 0, 1, 2, 1, 2, 1, 1, 1, 0, 1, 1, 0, 1, 1, 2, 1, 2, 1, 0,
       1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 0, 2, 1, 1, 2, 1, 0, 2, 0, 1, 0,
       1, 2, 2, 2, 1, 1, 2, 1, 1, 0, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 0, 1, 2, 2, 1, 2,
       1, 2, 2, 2, 2, 1, 2, 1, 2, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 1,
       2, 2, 1, 1, 1, 1, 2, 2, 1, 2, 2, 2, 1, 0, 1, 2, 2, 1, 1, 0, 0, 1,
       1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 0, 2, 1, 2, 2, 0, 2, 1, 1, 2,
       1, 2, 2, 0, 2, 1, 2, 2, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 2, 1, 2,
       2, 2, 2, 1, 1, 1, 1, 1, 0, 1, 0, 2, 0, 0, 0,

In [56]:
from sklearn.model_selection import train_test_split
X=df['ISRI_Stemmer']
X_train , X_test, y_train , y_test = train_test_split(X,y, test_size=0.2)
X_train

212    روب_المحبه_والمودهقروب_فيدرر_للدعمعبارة ريح ال...
615                طبق حول درويد كمل جهز كمبيوتر لتح نكس
300    ولل عيب قام طقطق علي حد يشف حل مهدي_علي_برع ان...
540          طن_حر عين رلم هيلارى رشق دونالد بته قله نسء
562                           يدو مايكروسوفت تطر رسم لءم
                             ...                        
579                  ويتسو_خبر رنمج قيس سرع نرن أصبح تاح
441                              لله عاي يكك ومع عوذ سحر
27                                            نساءالسلعة
307    معقوووولة لعب هالحجم غيب لعب هاللاعب يخي شلن ت...
653                                  لام علي حدث ىمج حين
Name: ISRI_Stemmer, Length: 529, dtype: object

<h2>KNeighborsClassifier<h2>

In [96]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
clf = KNeighborsClassifier()

X_train = count_vect_word.fit_transform(X_train)
X_test = count_vect_word.transform(X_test)
clf.fit(X_train , y_train)
y_predict = clf.predict(X_test)


print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))
print(accuracy_score(y_test, y_predict))

AttributeError: 'numpy.ndarray' object has no attribute 'lower'

<h2>DecisionTreeClassifier<h2>

In [60]:
from sklearn.model_selection import train_test_split
X=df['ISRI_Stemmer']
X_train , X_test, y_train , y_test = train_test_split(X,y, test_size=0.2)

clf = DecisionTreeClassifier()
X_train = count_vect_word.fit_transform(X_train)
X_test = count_vect_word.transform(X_test)
clf.fit(X_train , y_train)
y_predict = clf.predict(X_test)

print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))
print(accuracy_score(y_test, y_predict))

[[ 6 15  2]
 [ 9 43 12]
 [ 4 19 23]]
              precision    recall  f1-score   support

           0       0.32      0.26      0.29        23
           1       0.56      0.67      0.61        64
           2       0.62      0.50      0.55        46

    accuracy                           0.54       133
   macro avg       0.50      0.48      0.48       133
weighted avg       0.54      0.54      0.53       133

0.5413533834586466


C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)


<h2>RandomForestClassifier<h2>

In [61]:
from sklearn.model_selection import train_test_split
X=df['ISRI_Stemmer']
X_train , X_test, y_train , y_test = train_test_split(X,y, test_size=0.2)

clf = RandomForestClassifier()
X_train = count_vect_word.fit_transform(X_train)
X_test = count_vect_word.transform(X_test)
clf.fit(X_train , y_train)
y_predict = clf.predict(X_test)

print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))
print(accuracy_score(y_test, y_predict))

[[ 7 11  6]
 [ 3 40 20]
 [ 1 19 26]]
              precision    recall  f1-score   support

           0       0.64      0.29      0.40        24
           1       0.57      0.63      0.60        63
           2       0.50      0.57      0.53        46

    accuracy                           0.55       133
   macro avg       0.57      0.50      0.51       133
weighted avg       0.56      0.55      0.54       133

0.5488721804511278


C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:489: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_store_unique_indices = np.zeros(y.shape, dtype=np.int)
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builti

<h2>SVC<h2>

In [63]:
from sklearn.model_selection import train_test_split
X=df['ISRI_Stemmer']
X_train , X_test, y_train , y_test = train_test_split(X,y, test_size=0.2)

clf = SVC()
X_train = count_vect_word.fit_transform(X_train)
X_test = count_vect_word.transform(X_test)
clf.fit(X_train , y_train)
y_predict = clf.predict(X_test)

print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))
print(accuracy_score(y_test, y_predict))

[[ 0 30  0]
 [ 0 59  0]
 [ 0 44  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        30
           1       0.44      1.00      0.61        59
           2       0.00      0.00      0.00        44

    accuracy                           0.44       133
   macro avg       0.15      0.33      0.20       133
weighted avg       0.20      0.44      0.27       133

0.44360902255639095


C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [19]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))
print(accuracy_score(y_test, y_predict))

[[ 0 14  9]
 [ 0 32 30]
 [ 0 20 28]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        23
           1       0.48      0.52      0.50        62
           2       0.42      0.58      0.49        48

    accuracy                           0.45       133
   macro avg       0.30      0.37      0.33       133
weighted avg       0.38      0.45      0.41       133

0.45112781954887216


C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


<h1>TF-IDF with N-grams<h1>

In [64]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from nltk.tokenize import sent_tokenize

tfidf_transformer = TfidfTransformer()
tf_idf_vect = TfidfVectorizer(
                    ngram_range = (1,3),
                    max_features = 40000)





<h2>KNeighborsClassifier<h2>

In [67]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
X = df['ISRI_Stemmer']
X_train , X_test, y_train , y_test = train_test_split(X,y, test_size=0.2)

clf = KNeighborsClassifier()


X_train = tf_idf_vect.fit_transform(X_train)
X_test = tf_idf_vect.transform(X_test)
clf.fit(X_train, y_train)

print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))
print(accuracy_score(y_test, y_predict))

[[ 0 29  0]
 [ 0 61  0]
 [ 0 43  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        29
           1       0.46      1.00      0.63        61
           2       0.00      0.00      0.00        43

    accuracy                           0.46       133
   macro avg       0.15      0.33      0.21       133
weighted avg       0.21      0.46      0.29       133

0.45864661654135336


C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\neighbors\base.py:908: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  self._y = np.empty(y.shape, dtype=np.int)
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


<h2>DecisionTreeClassifier<h2>

In [68]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
X = df['ISRI_Stemmer']
X_train , X_test, y_train , y_test = train_test_split(X,y, test_size=0.2)

clf = DecisionTreeClassifier()


X_train = tf_idf_vect.fit_transform(X_train)
X_test = tf_idf_vect.transform(X_test)
clf.fit(X_train, y_train)

print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))
print(accuracy_score(y_test, y_predict))

[[ 0 22  0]
 [ 0 62  0]
 [ 0 49  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        22
           1       0.47      1.00      0.64        62
           2       0.00      0.00      0.00        49

    accuracy                           0.47       133
   macro avg       0.16      0.33      0.21       133
weighted avg       0.22      0.47      0.30       133

0.46616541353383456


C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


<h2>RandomForestClassifier<h2>

In [69]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
X = df['ISRI_Stemmer']
X_train , X_test, y_train , y_test = train_test_split(X,y, test_size=0.2)

clf = RandomForestClassifier()


X_train = tf_idf_vect.fit_transform(X_train)
X_test = tf_idf_vect.transform(X_test)
clf.fit(X_train, y_train)

print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))
print(accuracy_score(y_test, y_predict))

[[ 0 24  0]
 [ 0 67  0]
 [ 0 42  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        24
           1       0.50      1.00      0.67        67
           2       0.00      0.00      0.00        42

    accuracy                           0.50       133
   macro avg       0.17      0.33      0.22       133
weighted avg       0.25      0.50      0.34       133

0.5037593984962406


C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:489: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_store_unique_indices = np.zeros(y.shape, dtype=np.int)
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builti

<h2>SVC<h2>

In [70]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
X = df['ISRI_Stemmer']
X_train , X_test, y_train , y_test = train_test_split(X,y, test_size=0.2)

clf = SVC()


X_train = tf_idf_vect.fit_transform(X_train)
X_test = tf_idf_vect.transform(X_test)
clf.fit(X_train, y_train)

print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))
print(accuracy_score(y_test, y_predict))

[[ 0 21  0]
 [ 0 77  0]
 [ 0 35  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        21
           1       0.58      1.00      0.73        77
           2       0.00      0.00      0.00        35

    accuracy                           0.58       133
   macro avg       0.19      0.33      0.24       133
weighted avg       0.34      0.58      0.42       133

0.5789473684210527


C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


<h1>Bag OF Words <h1>

In [77]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.corpus import stopwords

vectorizer = CountVectorizer(max_features=1500, min_df=5, max_df=0.7, stop_words=stopwords.words('arabic'))
X = vectorizer.fit_transform(my_list).toarray()

In [78]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidfconverter = TfidfTransformer()
X = tfidfconverter.fit_transform(X).toarray()

In [79]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print(len(X_train[0]))
X_train[0]

248


array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.46076103, 0.        ,
       0.        , 0.        , 0.47211829, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

<h2>KNeighborsClassifier<h2>

In [83]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

X = tfidfconverter.fit_transform(X).toarray()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
classifier = KNeighborsClassifier()
classifier.fit(X_train, y_train) 
y_pred = classifier.predict(X_test)


print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[ 5 13 18]
 [ 4 28 27]
 [ 4 14 20]]
              precision    recall  f1-score   support

           0       0.38      0.14      0.20        36
           1       0.51      0.47      0.49        59
           2       0.31      0.53      0.39        38

    accuracy                           0.40       133
   macro avg       0.40      0.38      0.36       133
weighted avg       0.42      0.40      0.38       133

0.39849624060150374


C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\neighbors\base.py:908: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  self._y = np.empty(y.shape, dtype=np.int)


<h2>DecisionTreeClassifier<h2>

In [84]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

X = tfidfconverter.fit_transform(X).toarray()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train) 
y_pred = classifier.predict(X_test)


print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[ 9 13 14]
 [ 3 26 30]
 [ 1  9 28]]
              precision    recall  f1-score   support

           0       0.69      0.25      0.37        36
           1       0.54      0.44      0.49        59
           2       0.39      0.74      0.51        38

    accuracy                           0.47       133
   macro avg       0.54      0.48      0.45       133
weighted avg       0.54      0.47      0.46       133

0.47368421052631576


C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)


<h2>RandomForestClassifier<h2>

In [80]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=1000, random_state=0)
classifier.fit(X_train, y_train) 

C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:489: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_store_unique_indices = np.zeros(y.shape, dtype=np.int)
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review you

C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, chec

C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, chec

C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, chec

C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, chec

C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, chec

C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, chec

C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, chec

C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, chec

C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, chec

C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, chec

C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, chec

C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, chec

C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, chec

C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, chec

C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, chec

C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, chec

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [81]:
y_pred = classifier.predict(X_test)
y_pred

C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\ensemble\base.py:158: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int)


array([1, 2, 1, 1, 0, 2, 0, 2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 2, 2, 1, 1,
       2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 2, 2, 1, 2, 0, 1, 1, 2, 2, 2,
       2, 1, 0, 2, 1, 1, 2, 2, 2, 1, 1, 1, 2, 1, 2, 1, 1, 2, 2, 1, 2, 1,
       1, 2, 2, 1, 2, 2, 2, 0, 2, 2, 1, 2, 0, 2, 2, 2, 2, 2, 1, 2, 0, 1,
       2, 1, 2, 2, 1, 1, 1, 2, 2, 2, 0, 1, 1, 1, 1, 1, 2, 2, 0, 1, 1, 2,
       0, 0, 0, 2, 1, 1, 1, 0, 1, 2, 2, 1, 1, 0, 1, 1, 1, 0, 1, 2, 1, 1,
       2])

In [29]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[ 9 19  8]
 [ 5 30 24]
 [ 1 13 24]]
              precision    recall  f1-score   support

           0       0.60      0.25      0.35        36
           1       0.48      0.51      0.50        59
           2       0.43      0.63      0.51        38

    accuracy                           0.47       133
   macro avg       0.50      0.46      0.45       133
weighted avg       0.50      0.47      0.46       133

0.47368421052631576


<h2>SVC<h2>

In [85]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

X = tfidfconverter.fit_transform(X).toarray()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
classifier = SVC()
classifier.fit(X_train, y_train) 
y_pred = classifier.predict(X_test)


print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[ 0 36  0]
 [ 0 59  0]
 [ 0 38  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        36
           1       0.44      1.00      0.61        59
           2       0.00      0.00      0.00        38

    accuracy                           0.44       133
   macro avg       0.15      0.33      0.20       133
weighted avg       0.20      0.44      0.27       133

0.44360902255639095


C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


<h1> tests<h1>

In [29]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from nltk.classify.scikitlearn import SklearnClassifier
from sklearn.svm import SVC

In [30]:
names = ["K Nearest Neighbors", "Decision Tree", "Random Forest", "Logistic Regression", "SGD Classifier",
         "Naive Bayes", "SVM Linear"]

classifiers = [
    KNeighborsClassifier(),
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    LogisticRegression(),
    SGDClassifier(max_iter = 100),
    MultinomialNB(),
    SVC(kernel = 'linear')
]

models = zip(names, classifiers)

In [36]:
y = l.fit_transform(df[['feeling']])
X=df['ISRI_Stemmer']
featuresets = X, y

In [45]:
from sklearn.model_selection import train_test_split
from sklearn import model_selection
training, testing = model_selection.train_test_split(featuresets, test_size = 0.25, random_state=0)
testing


[array([2, 1, 2, 1, 1, 1, 2, 2, 2, 1, 1, 2, 1, 2, 2, 1, 2, 2, 1, 1, 1, 1,
        1, 2, 1, 1, 2, 2, 0, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 0, 1, 2, 1, 2,
        2, 1, 2, 1, 2, 1, 2, 2, 1, 0, 1, 2, 2, 2, 2, 1, 2, 2, 0, 1, 2, 2,
        2, 1, 2, 1, 1, 1, 2, 1, 1, 0, 1, 0, 1, 0, 1, 2, 2, 2, 1, 1, 2, 1,
        2, 1, 1, 1, 2, 2, 0, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1,
        2, 1, 2, 0, 1, 2, 1, 2, 1, 1, 1, 0, 1, 1, 0, 1, 1, 2, 1, 2, 1, 0,
        1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 0, 2, 1, 1, 2, 1, 0, 2, 0, 1, 0,
        1, 2, 2, 2, 1, 1, 2, 1, 1, 0, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 0, 1, 2, 2, 1, 2,
        1, 2, 2, 2, 2, 1, 2, 1, 2, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 1,
        2, 2, 1, 1, 1, 1, 2, 2, 1, 2, 2, 2, 1, 0, 1, 2, 2, 1, 1, 0, 0, 1,
        1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 0, 2, 1, 2, 2, 0, 2, 1, 1, 2,
        1, 2, 2, 0, 2, 1, 2, 2, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 2, 1, 2,
        2, 2, 2, 1, 1, 1, 1, 1, 0, 1, 

In [43]:

for name, model in models:
    nltk_model = SklearnClassifier(model)
    nltk_model.train(training[0])
    accuracy = nltk.classify.accuracy(nltk_model, testing)*100
    print("{} Accuracy: {}".format(name, accuracy))

ValueError: too many values to unpack (expected 2)

In [32]:
!pip install gensim==3.8.3

  Found existing installation: Cython 0.29.21
    Uninstalling Cython-0.29.21:
      Successfully uninstalled Cython-0.29.21
  Found existing installation: gensim 3.4.0
    Uninstalling gensim-3.4.0:
      Successfully uninstalled gensim-3.4.0


<h1>Word2Vec<h1>

In [2]:
from sklearn.preprocessing import LabelEncoder
y = LabelEncoder().fit_transform(df['ISRI_Stemmer'])
y

array([328, 174, 281, 255,   2, 342, 393, 115, 380, 321, 320, 611, 600,
        50, 547, 177, 175, 119,  72, 324, 453, 411, 491,  29, 221, 588,
        52, 525, 513, 418,  34, 344, 553, 295, 149,  95,  86, 354,   4,
        79, 469,  85, 659, 256, 581, 330, 187, 420, 399, 602, 594, 593,
       247, 404, 103, 392,  80, 318, 517, 519, 439, 317,  82, 654, 126,
       474, 283, 492, 577, 352,  24, 573, 508, 490, 307,  48, 583,  33,
       171, 253, 252, 479, 326, 614, 613, 134, 215, 563, 559, 278, 621,
       515, 648, 210,  45, 216,  53, 155, 160, 504, 335,  83, 341, 415,
       534, 475,  73, 541, 271, 102, 572, 423, 163, 482, 350, 217, 188,
       353, 282, 571, 528,  10, 288, 578, 407, 312, 183, 331, 173,  55,
       421, 308, 165, 549, 169, 152, 574,  87, 170, 402, 273,  66, 591,
       306, 576, 518, 140, 178, 362, 285, 122, 533, 633, 561, 499, 186,
       582, 610,  68, 575, 181, 289, 472, 254, 585, 537, 539, 227, 597,
       390,  63, 196, 435, 172,  60,  58, 543, 108,  62, 384, 24

In [3]:
from sklearn.model_selection import train_test_split
X = df['ISRI_Stemmer']
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.2)

In [4]:
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize


model = Word2Vec(X_train.apply( word_tokenize), min_count=1, size=100)
w2v = dict(zip(model.wv.index2word,model.wv.syn0))

print(model)

words = list(model.wv.vocab)
print(words)


model.save('model.bin')

new_model = Word2Vec.load('model.bin')
print(new_model)



C:\Users\THE WOLF\Anaconda3\lib\site-packages\requests\__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.4) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\feature_extraction\image.py:167: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int):
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:30: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by it

Word2Vec(vocab=2176, size=100, alpha=0.025)
['صور', 'طرق', 'رقي', 'اري', 'كأس', 'خمر', 'ائم', 'بدأ', 'صغر', 'جدد', 'ويندوزنسخة', 'منت', 'فهد', 'طلع', 'خلف', 'تما', 'خبر', 'كنولوج', 'هتف', 'يحتاجدقيقة', 'شحن', 'لال', 'نظر', 'رئس', 'ميلانيا_ترامب', 'ألق', 'صمم', 'بهظ', 'ن', 'فضو', 'ملل', 'نطر', 'ديشامب', 'ماكوووو', 'شغل', 'عجججججججيب', 'هالانس', 'ولل', 'فهم', 'ركز', 'كلم', 'درر', 'دب', 'خلج', 'طير', 'امر', 'غوغل', 'طلق', 'حتفل', 'بعم', 'قرء', 'هيه', 'احس', 'مرا', 'تأثر', 'فلم', 'هييه_رادع_لكل_اعدا_الوطن', 'قل', 'اعل', 'ؤسس', 'ويكيليكس', 'مهم', 'اليوم', 'لند', 'برل', 'يخص', 'ذكر', 'قرح', 'هجم', 'بطر', 'طر', 'مبو', 'يحك', 'عطر', 'طلل', 'قمت', 'نجم', 'غال', 'غدت', 'بطل', 'وند', 'ساط_أحمدي', 'دهش', 'صدف', 'سور', 'ثيقف', 'ريد', 'عفش', 'بضع', 'علم', 'ثقف', 'عمك', 'س_اقوللاتفرح', 'كثر', 'رشح', 'سمح', 'ونف', 'دخل', 'قرن', 'هالجحلط', 'بلز', 'يعن', 'ارد', 'نعل', 'دتي', 'ربم', 'ضرب', 'عهم', 'رأي', 'خرج', 'لأل', 'مرة', 'نعم', 'نهي', 'جيل', 'عظم', 'شكر', 'حبه', 'زي', 'تحب', 'رشلو', 'انت', 'اي', 'عمم'

C:\Users\THE WOLF\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.vectors instead).
  


## Embedding Vectorizers

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer
from collections import defaultdict


## define two classes to write functions of fit & transform (to be able to include w2v in pipeline)
class MeanEmbeddingVectorizer(object):
    def __init__(self, word2vec):
        self.word2vec = word2vec
        # if a text is empty we should return a vector of zeros
        # with the same dimensionality as all the other vectors
        self.dim = len(word2vec.items())

    def fit(self, X, y):
        return self

    def transform(self, X):
        return np.array([
            np.mean([self.word2vec[w] for w in words if w in self.word2vec]
                    or [np.zeros(self.dim)], axis=0)
            for words in X
        ])
    
    
class TfidfEmbeddingVectorizer(object):
    def __init__(self, word2vec):
        self.word2vec = word2vec
        self.word2weight = None
        self.dim = len(word2vec.items())

    def fit(self, X, y):
        tfidf = TfidfVectorizer(analyzer=lambda x: x)
        tfidf.fit(X)
        # if a word was never seen - it must be at least as infrequent
        # as any of the known words - so the default idf is the max of 
        # known idf's
        max_idf = max(tfidf.idf_)
        self.word2weight = defaultdict(
            lambda: max_idf,
            [(w, tfidf.idf_[i]) for w, i in tfidf.vocabulary_.items()])

        return self

    def transform(self, X):
        return np.array([
                np.mean([self.word2vec[w] * self.word2weight[w]
                         for w in words if w in self.word2vec] or
                        [np.zeros(self.dim)], axis=0)
                for words in X
            ])
    

In [6]:
def stem_text(text):
    import nltk
    from nltk.tokenize import word_tokenize
    from nltk.stem.isri import ISRIStemmer

    stemmer = ISRIStemmer()
    tokens = word_tokenize(text)
    
    return ' '.join([stemmer.stem(t) for t in tokens])

<h1>Models<h1>

In [8]:
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier

scv_clf = SVC()
DT_clf = DecisionTreeClassifier(criterion='entropy', max_depth=4)
Ada_clf = AdaBoostClassifier(n_estimators=100)
KNN_clf = KNeighborsClassifier( n_neighbors=5)
RF_clf = RandomForestClassifier()

In [9]:
from sklearn.metrics import classification_report  
def print_measures(y_test, y_pred):
    print(classification_report(y_test, y_pred))

In [95]:
from sklearn.pipeline import Pipeline
import numpy as np

#Define Pipeline
word2vec_pipeline = MeanEmbeddingVectorizer(w2v)

#train
word2vec_pipeline.fit(X_train,y_train)
word2vec_pipeline.fit_transform(X_train,y_train)
#test
print('For word2vec__pipeline')
print_measures(y_test, word2vec_pipeline.predict(X_test))


AttributeError: 'MeanEmbeddingVectorizer' object has no attribute 'fit_transform'

<h1>Gloves<h1>

In [87]:
##Gloves
with open(r"C:\gloves_vectors.txt", "rb") as lines:
    gloves = {line.split()[0]: np.array(map(float, line.split()[1:]))
           for line in lines}
gloves

{b'\xd9\x85\xd9\x86': array(<map object at 0x0000020D97A0B2C8>, dtype=object),
 b'\xd9\x81\xd9\x8a': array(<map object at 0x0000020D97A0BF48>, dtype=object),
 b'\xd8\xb9\xd9\x84\xd9\x89': array(<map object at 0x0000020D976DD988>, dtype=object),
 b'\xd8\xa7\xd9\x86': array(<map object at 0x0000020D976DD2C8>, dtype=object),
 b'\xd8\xa7\xd9\x84\xd9\x84\xd9\x87': array(<map object at 0x0000020D976DD288>, dtype=object),
 b'\xd9\x88': array(<map object at 0x0000020D976DD188>, dtype=object),
 b'\xd9\x84\xd8\xa7': array(<map object at 0x0000020D976DDF08>, dtype=object),
 b'..': array(<map object at 0x0000020D976DD7C8>, dtype=object),
 b'\xd9\x86\xd9\x81\xd8\xb3\xd8\xa7\xd9\x86\xd9\x8a': array(<map object at 0x0000020D976DD5C8>, dtype=object),
 b'\xd8\xa7\xd9\x84\xd9\x85\xd8\xb5\xd8\xaf\xd8\xb1:': array(<map object at 0x0000020D9791A748>, dtype=object),
 b'\xd9\x85\xd8\xa7': array(<map object at 0x0000020D9791A688>, dtype=object),
 b'\xd8\xa7\xd9\x86\xd8\xa7': array(<map object at 0x0000020D979

In [90]:
from sklearn.pipeline import Pipeline

#Define Pipeline
gloves_pipeline =Pipeline([('gloves', MeanEmbeddingVectorizer(gloves)),('DT_clf', DT_clf)])

#train
gloves_pipeline.fit(X_train,y_train)

#test
print('For gloves__pipeline')
print_measures(y_test, gloves_pipeline.predict(X_test))


For gloves__pipeline
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        36
           1       0.44      1.00      0.61        59
           2       0.00      0.00      0.00        38

    accuracy                           0.44       133
   macro avg       0.15      0.33      0.20       133
weighted avg       0.20      0.44      0.27       133



C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\THE WOLF\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [ ]:
from transformers import DistilBertConfig, TFDistilBertModel
import tensorflow as tf

distile_bert='distilbert-base-uncased'

config=DistilBertConfig(dropout=0.2, attention_dropout=0.2)
config.output_hiddenstates=False
transformer_model=TFDistilBertModel.from_pretrained(distile_bert, config=config)

input_ids_in= tf.keras.layers.Input(shape=(128,), name='input_token', dtype=('int32'))
input_masks_in= tf.keras.layers.Input(shape=(128,), name='masked_token', dtype=('int32'))

embedding_layer=transformer_model(input_ids_in, attention_mask=input_masks_in)[0]
cls_token=embedding_layer[:,0,:]
X=tf.keras.layers.BatchNormalization()(cls_token)
X=tf.keras.layers.Dense(192,activation='relu')(X)
X=tf.keras.layers.Dropout(0.2)(X)
X=tf.keras.layers.Dense(6,activation='softmax')(X)
model=tf.keras.Model(inputs=[input_ids_in, input_masks_in], outputs =X)